In [1]:
import numpy as np

In [8]:
arr_list = np.array([1, 2, 3, 4]) # из списка в массив NumPy
arr_list

array([1, 2, 3, 4])

In [9]:
arr_zeros = np.zeros(10) # массив из 10 нулевых элементов
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr_arange = np.arange(1, 10, 0.1) # генерация массива последовательности в диапазоне [1; 10) с шагом 0.1
arr_arange

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [12]:
arr_arange.shape # размерность массива, его "форма"

(90,)

In [14]:
arr_arange.dtype # тип данных элементов массива - float64

dtype('float64')

In [15]:
matrix = np.arange(1, 10, 0.1).reshape(9, 10) # изменение "формы" массива и превращение в матрицу
matrix

array([[1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

In [17]:
matrix[1:3] # первая и вторая строки матрицы

array([[2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]])

In [18]:
matrix[1, 3:5] # третий и четвертый элементы первой строки

array([2.3, 2.4])

In [20]:
matrix[1, 1] # первый элемент первой строки

np.float64(2.100000000000001)

In [22]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]).reshape(3, 1)
a @ b # произведение векторов (по сути, скалярное произведение)

array([14])

In [24]:
a + b.T # сумма двух векторов

array([[2, 4, 6]])

In [25]:
a.mean() # среднее арифметическое

np.float64(2.0)

In [27]:
np.median(a) # медиана

np.float64(2.0)